name: CI/CD for Earthquake Prediction Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Linting and Testing
      - name: Run Linter
        run: |
          pip install flake8
          flake8 --max-line-length=88 .

      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest tests/

  dockerize:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/earthquake-prediction:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/earthquake-prediction:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      # Simulate Deployment (or use actual cloud deployment steps)
      - name: Deploy Application
        run: echo "Deploying to production..."
