name: CI/CD for Earthquake Prediction Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest tests/

  dockerize:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t hasnainshinwari/eco-forcast:latest .
          docker push hasnainshinwari/eco-forcast:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Deploy Application
        run: echo "Deploying to production..."
