name: CI/CD for Earthquake Prediction Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  dockerize:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t hasnainshinwari/eco-forcast:latest .
          docker push hasnainshinwari/eco-forcast:latest

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade

      - name: Deploy to Elastic Beanstalk
        env:
          DOCKER_IMAGE: hasnainshinwari/eco-forcast:latest
        run: |
          eb init -p docker eco-forecast-app --region us-east-1
          eb use eco-forecast-env # Replace with your Elastic Beanstalk environment name
          echo "docker:
            image: $DOCKER_IMAGE" > Dockerrun.aws.json
          eb deploy

